version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lunch_place
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: always
    hostname: db
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/lunch_place
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: